version: "3.8"

services:
  pihole:
    image: pihole/pihole:2025.01
    container_name: pihole
    network_mode: "host"              # binds DNS directly on the host (53/udp,tcp)
    restart: unless-stopped
    environment:
      TZ: "UTC"                       # change if you want
      WEBPASSWORD: "changeme"
      WEB_PORT: "8088"                # avoid conflict with Traefik on :80
      DNSMASQ_USER: "root"
      DNSMASQ_LISTENING: "all"
      FTLCONF_LOCAL_IPV4: "192.168.2.50"   # IP of this node
      PIHOLE_DNS_: "1.1.1.1;1.0.0.1"       # upstream resolvers
    volumes:
      - pihole_etc:/etc/pihole
      - dnsmasq_etc:/etc/dnsmasq.d
    # No DHCP here (port 67). If you ever need DHCP, add NET_ADMIN and config later.

volumes:
  pihole_etc:
  dnsmasq_etc:
