version: "3.8"

services:
  pihole:
    image: pihole/pihole:2025.01
    environment:
      TZ: "Europe/Amsterdam"
      WEBPASSWORD: "changeme"
      DNSMASQ_USER: "root"
      DNSMASQ_LISTENING: "all"
      FTLCONF_LOCAL_IPV4: "192.168.2.50"   # LAN IP of the chosen node
      PIHOLE_DNS_: "1.1.1.1;1.0.0.1"
    volumes:
      - pihole_etc:/etc/pihole
      - dnsmasq_etc:/etc/dnsmasq.d
    # Publish DNS directly on the host of this task (no routing mesh)
    ports:
      - target: 53
        published: 53
        protocol: tcp
        mode: host
      - target: 53
        published: 53
        protocol: udp
        mode: host
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.id == REPLACE_WITH_NODE_ID   # <- put your manager's node ID here

volumes:
  pihole_etc:
  dnsmasq_etc:
